--Device types
GCHROMA_DEVICE_ALL = -1
GCHROMA_DEVICE_MOTHERBOARD = 0
GCHROMA_DEVICE_RAM = 1
GCHROMA_DEVICE_GPU = 2
GCHROMA_DEVICE_COOLER = 3
GCHROMA_DEVICE_LEDSTRIP = 4
GCHROMA_DEVICE_KEYBOARD = 5
GCHROMA_DEVICE_MOUSE = 6
GCHROMA_DEVICE_MOUSEMAT = 7
GCHROMA_DEVICE_HEADSET = 8
GCHROMA_DEVICE_HEADSETSTAND = 9
GCHROMA_DEVICE_GAMEPAD = 10
GCHROMA_DEVICE_LIGHT = 11
GCHROMA_DEVICE_SPEAKER = 12
GCHROMA_DEVICE_VIRTUAL = 13
GCHROMA_DEVICE_UNKNOWN = 14

--Colors
GCHROMA_COLOR_BLACK = Vector( 0, 0, 0 )
GCHROMA_COLOR_WHITE = Vector( 255, 255, 255 )
GCHROMA_COLOR_RED = Vector( 255, 0, 0 )
GCHROMA_COLOR_GREEN = Vector( 0, 255, 0 )
GCHROMA_COLOR_BLUE = Vector( 0, 0, 255 )
GCHROMA_COLOR_MAGENTA = Vector( 255, 0, 255 )
GCHROMA_COLOR_YELLOW = Vector( 255, 255, 0 )
GCHROMA_COLOR_CYAN = Vector( 0, 255, 255 )
GCHROMA_COLOR_ORANGE = Vector( 255, 89, 0 )
GCHROMA_COLOR_LIGHTGRAY = Vector( 170, 170, 170 )
GCHROMA_COLOR_DARKGRAY = Vector( 25, 25, 25 )
GCHROMA_COLOR_PINK = Vector( 255, 0, 89 )
GCHROMA_COLOR_PURPLE = Vector( 89, 0, 255 )
